const assert=require('node:assert/strict');
const values={};let failWrite=false;
global.wx={getStorageSync:k=>values[k],setStorageSync:(k,v)=>{if(failWrite&&k==='scheduleData')throw Error('存储空间不足');values[k]=JSON.parse(JSON.stringify(v));},removeStorageSync:k=>delete values[k]};
const backup=require('../miniprogram/utils/backup');
const storage=require('../miniprogram/utils/storage');
values.overrides={'2026-10-08':{type:'off',note:'停课'}};
values.courseChanges={'2026-09-21|c0':{source:'2026-09-21',courseId:'c0',type:'cancel'}};
assert.equal(storage.read().overrides['2026-10-08'].note,'停课');
assert.equal(values.scheduleData.version,1);
const exported=backup.encode(storage.read());
assert.deepEqual(backup.decode(exported).changes,values.courseChanges);
assert.throws(()=>backup.decode('bad json'));
assert.throws(()=>backup.decode(JSON.stringify({...JSON.parse(exported),version:99})));
assert.throws(()=>backup.decode(JSON.stringify({...JSON.parse(exported),term:'2027-2028-1'})));
assert.throws(()=>backup.decode(JSON.stringify({...JSON.parse(exported),changes:{'x':{type:'cancel'}}})));
assert.throws(()=>backup.decode('x'.repeat(300001)));
const imported={overrides:{'2026-10-10':{type:'off',note:'外部备份'}},changes:{}};
storage.importBackup(backup.encode(imported));
assert.equal(storage.read().overrides['2026-10-10'].note,'外部备份');
assert(values.backupBeforeImport);
storage.undoImport();
assert.equal(storage.read().overrides['2026-10-08'].note,'停课');
assert.equal(values.backupBeforeImport,undefined);
const before=JSON.stringify(storage.read());failWrite=true;
assert.throws(()=>storage.importBackup(backup.encode(imported)));
assert.equal(JSON.stringify(storage.read()),before);failWrite=false;
const invalid=JSON.parse(exported);invalid.changes={'2026-09-21|c0':{source:'2026-09-21',courseId:'c0',type:'move',target:'2026-10-08',start:9,end:3}};
assert.throws(()=>backup.decode(JSON.stringify(invalid)));
assert.equal(values.overrides['2026-10-08'].note,'停课');
console.log('备份测试通过：旧数据迁移、导出导入、版本/学期/内容拒绝、撤销、写入失败保留原数据');
