const assert=require('node:assert/strict');
const values={};let pageDef;let toast;let tab;
global.Page=p=>{pageDef=p;};
global.wx={getStorageSync:k=>values[k],setStorageSync:(k,v)=>{values[k]=JSON.parse(JSON.stringify(v));},removeStorageSync:k=>{delete values[k];},showToast:r=>{toast=r.title;},switchTab:r=>{tab=r.url;},showModal:r=>r.success({confirm:true})};
function load(name){require('../miniprogram/pages/'+name+'/index');return Object.assign({},pageDef,{data:JSON.parse(JSON.stringify(pageDef.data||{})),setData(v){Object.assign(this.data,v);}});}
const today=load('today');today.load('2026-10-08');
assert.equal(today.data.courses.length,3);assert.equal(today.data.dates.length,7);
today.showDetail({currentTarget:{dataset:{uid:today.data.courses[0].uid}}});assert.equal(today.data.detailCourses.length,1);
today.editCourse({currentTarget:{dataset:{uid:today.data.detailCourses[0].uid}}});assert.equal(tab,'/pages/settings/index');
assert.equal(values.courseEditDraft.source,'2026-10-08');
const settings=load('settings');settings.onShow();
assert.equal(settings.data.selectedCourse.id,'c15');assert.equal(settings.data.editDate,'2026-10-08');
settings.setData({action:0,target:'2026-10-09',startIndex:4,endIndex:5,room:'测试教室'});settings.saveCourse();
assert.equal(toast,'已保存');assert.equal(require('../miniprogram/utils/storage').read().changes['2026-10-08|c15'].target,'2026-10-09');
assert.equal(settings.data.lastSavedDate,'2026-10-09');
settings.viewSaved();assert.equal(tab,'/pages/today/index');today.onShow();today.onHide();assert.equal(today.data.date,'2026-10-09');
today.load('2026-10-08');assert.equal(today.data.courses.length,2);
today.load('2026-10-09');assert(today.data.courses.some(c=>c.id==='c15'&&c.room==='测试教室'));
settings.removeCourse({currentTarget:{dataset:{key:'2026-10-08|c15'}}});
today.load('2026-10-08');assert.equal(today.data.courses.length,3);
settings.setData({editDate:'2026-10-08',courseIndex:0});settings.loadOptions();settings.setData({action:1});settings.saveCourse();
today.load('2026-10-08');assert.equal(today.data.courses.length,2);
const week=load('week');week.load('2026-09-30');
const wed=week.data.days.find(d=>d.date==='2026-09-30'),group=wed.groups.find(g=>g.count===3);
week.detail({currentTarget:{dataset:{date:wed.date,group:group.id}}});assert.equal(week.data.detailCourses.length,3);
settings.setData({editDate:'2026-10-08',courseIndex:0});settings.loadOptions();settings.setData({action:0,startIndex:9,endIndex:3});settings.saveCourse();assert(toast.includes('节次范围'));
assert.equal(settings.data.groups.single,true);assert.equal(settings.data.groups.day,false);
settings.toggleGroup({currentTarget:{dataset:{section:'day'}}});assert.equal(settings.data.groups.day,true);
let clipboard='';wx.setClipboardData=r=>{clipboard=r.data;if(r.success)r.success();};
settings.exportBackup();assert(clipboard.includes('heibeixue.timetable'));
const imported=require('../miniprogram/utils/backup').encode({overrides:{'2026-10-12':{type:'off',note:'导入测试'}},changes:{}});
settings.previewImport(imported);assert(require('../miniprogram/utils/storage').read().overrides['2026-10-12']);assert.equal(settings.data.hasUndoImport,true);
settings.undoBackup();assert(!require('../miniprogram/utils/storage').read().overrides['2026-10-12']);
const before=JSON.stringify(require('../miniprogram/utils/storage').read());settings.previewImport('坏备份');assert.equal(JSON.stringify(require('../miniprogram/utils/storage').read()),before);
const files={};let shared;
wx.env={USER_DATA_PATH:'/local'};
wx.getFileSystemManager=()=>({writeFileSync:(p,data)=>{files[p]=data;},readFile:r=>r.success({data:files[r.filePath]})});
wx.shareFileMessage=r=>{shared=r.filePath;};settings.shareBackup();assert(require('../miniprogram/utils/backup').decode(files[shared]));
files['/incoming.json']=imported;wx.chooseMessageFile=r=>r.success({tempFiles:[{path:'/incoming.json',size:imported.length}]});
settings.importFile();assert(require('../miniprogram/utils/storage').read().overrides['2026-10-12']);settings.undoBackup();
wx.showModal=r=>r.success({confirm:false});settings.previewImport(imported);assert.equal(JSON.stringify(require('../miniprogram/utils/storage').read()),before);
console.log('页面流程通过：详情、单门调课/恢复/取消、保存后返回、分组展开、备份复制/导入/撤销、无效备份不写入');
