const {today,stamp,daySchedule,slots,validateChange}=require('../../utils/schedule');
const storage=require('../../utils/storage');
const backup=require('../../utils/backup');
const {courses}=require('../../data/courses');
Page({data:{types:['停课 / 放假','按其他日期的课表上课'],type:0,date:today(),source:today(),note:'',editDate:today(),target:today(),actions:['调整时间 / 教室','取消本次课程'],action:0,courseIndex:0,periodOptions:Array.from({length:11},(_,i)=>'第'+(i+1)+'节'),startIndex:0,endIndex:1,room:'',groups:{single:true,records:false,day:false,times:false,backup:false},backupText:'',lastSavedDate:'',hasUndoImport:false},
 onShow(){try{this.refresh();const draft=wx.getStorageSync('courseEditDraft');if(draft){wx.removeStorageSync('courseEditDraft');this.setData({editDate:draft.source,groups:Object.assign({},this.data.groups,{single:true})});this.loadOptions(draft.courseId);}}catch(e){wx.showToast({title:e.message||'无法读取课程调整',icon:'none'});}},
 refresh(){const {overrides,changes}=storage.read();this.setData({rules:Object.keys(overrides).sort().map(date=>Object.assign({date},overrides[date])),courseRules:Object.keys(changes).sort().map(key=>{const r=changes[key],c=courses.find(c=>c.id===r.courseId);return Object.assign({key,name:c?c.name:'课程'},r);}),times:slots(today()).map((v,i)=>({period:i+1,time:v.join('—')})),hasUndoImport:!!wx.getStorageSync('backupBeforeImport')});this.loadOptions();},
 toggleGroup(e){const section=e.currentTarget.dataset.section;if(Object.prototype.hasOwnProperty.call(this.data.groups,section))this.setData({groups:Object.assign({},this.data.groups,{[section]:!this.data.groups[section]})});},
 viewSaved(){try{storage.viewDate(this.data.lastSavedDate);}catch(e){wx.showToast({title:'无法打开课程日期',icon:'none'});}},
 backupInput(e){this.setData({backupText:e.detail.value});},
 exportBackup(){try{const text=backup.encode(storage.read());this.setData({backupText:text});wx.setClipboardData({data:text,success:()=>wx.showToast({title:'备份已复制'}),fail:()=>wx.showToast({title:'复制失败，可长按备份文本复制',icon:'none'})});}catch(e){wx.showToast({title:e.message,icon:'none'});}},
 shareBackup(){try{const text=backup.encode(storage.read());this.setData({backupText:text});if(!wx.shareFileMessage||!wx.getFileSystemManager){wx.showToast({title:'请使用复制备份文本',icon:'none'});return;}const filePath=wx.env.USER_DATA_PATH+'/heibeixue-timetable-2026-2027-1.json';wx.getFileSystemManager().writeFileSync(filePath,text,'utf8');wx.shareFileMessage({filePath,fileName:'黑背雪课表备份.json',fail:e=>{if(!/cancel/i.test(e.errMsg||''))wx.showToast({title:'分享失败，请复制备份文本',icon:'none'});}});}catch(e){wx.showToast({title:'备份文件生成失败，请复制文本',icon:'none'});}},
 importFile(){if(!wx.chooseMessageFile){wx.showToast({title:'请粘贴备份文本导入',icon:'none'});return;}wx.chooseMessageFile({count:1,type:'file',extension:['json'],success:result=>{const file=result.tempFiles&&result.tempFiles[0];if(!file)return;if(file.size>1000000){wx.showToast({title:'备份文件过大',icon:'none'});return;}wx.getFileSystemManager().readFile({filePath:file.path,encoding:'utf8',success:r=>this.previewImport(r.data),fail:()=>wx.showToast({title:'无法读取文件，请粘贴备份文本',icon:'none'})});},fail:e=>{if(!/cancel/i.test(e.errMsg||''))wx.showToast({title:'文件选择失败，请粘贴备份文本',icon:'none'});}});},
 importText(){this.previewImport(this.data.backupText);},
 pasteBackup(){wx.getClipboardData({success:r=>this.setData({backupText:r.data||''}),fail:()=>wx.showToast({title:'无法读取剪贴板，可手动粘贴',icon:'none'})});},
 previewImport(text){try{const next=backup.decode(text),current=storage.read();wx.showModal({title:'恢复备份并覆盖当前调整？',content:'备份：'+Object.keys(next.overrides).length+'条整天调整、'+Object.keys(next.changes).length+'条单门调整。\n本机：'+Object.keys(current.overrides).length+'条整天调整、'+Object.keys(current.changes).length+'条单门调整。\n将先保留本机数据，可撤销最近一次导入。',confirmText:'恢复备份',success:r=>{if(r.confirm){try{storage.importBackup(text);this.refresh();this.setData({backupText:'',lastSavedDate:''});wx.showToast({title:'备份已恢复'});}catch(e){wx.showToast({title:'导入失败，原数据仍保留',icon:'none'});}}}});}catch(e){wx.showToast({title:e.message,icon:'none'});}},
 undoBackup(){wx.showModal({title:'撤销最近一次导入？',content:'恢复到导入之前的调整。导入后新做的调整也会被替换。',success:r=>{if(r.confirm){try{storage.undoImport();this.refresh();this.setData({lastSavedDate:''});wx.showToast({title:'已撤销导入'});}catch(e){wx.showToast({title:e.message,icon:'none'});}}}});},
 loadOptions(id){const {overrides,changes}=storage.read(),options=daySchedule(this.data.editDate,overrides).courses;let index=id?options.findIndex(c=>c.id===id):this.data.courseIndex;index=Math.max(0,Math.min(index,options.length-1));const course=options[index],rule=course&&changes[this.data.editDate+'|'+course.id];this.setData({options,courseNames:options.map(c=>c.name+' · '+c.period),courseIndex:index,selectedCourse:course||null,target:rule&&rule.type==='move'?rule.target:this.data.editDate,action:rule&&rule.type==='cancel'?1:0,startIndex:(rule&&rule.type==='move'?rule.start:course?course.start:1)-1,endIndex:(rule&&rule.type==='move'?rule.end:course?course.end:2)-1,room:rule&&rule.type==='move'?rule.room:course?course.room:''});},
 editDate(e){this.setData({editDate:e.detail.value,courseIndex:0});this.loadOptions();},course(e){this.setData({courseIndex:Number(e.detail.value)});this.loadOptions();},target(e){this.setData({target:e.detail.value});},action(e){this.setData({action:Number(e.detail.value)});},start(e){this.setData({startIndex:Number(e.detail.value)});},end(e){this.setData({endIndex:Number(e.detail.value)});},room(e){this.setData({room:e.detail.value});},
 saveCourse(){try{const c=this.data.selectedCourse;if(!c)throw Error('请先选择有课程的日期');const {overrides,changes}=storage.read();const r={source:this.data.editDate,courseId:c.id,type:this.data.action===1?'cancel':'move'};if(r.type==='move')Object.assign(r,{target:this.data.target,start:this.data.startIndex+1,end:this.data.endIndex+1,room:this.data.room.trim()||c.room});validateChange(r,overrides);const preview=Object.assign({},changes,{[r.source+'|'+r.courseId]:r});const targetSchedule=daySchedule(r.target||r.source,overrides,preview);const warnings=[];if(r.type==='move'){if(overrides[r.target]&&overrides[r.target].type==='off')warnings.push('目标日期整天停课，课程暂不会显示。');else if(targetSchedule.notice)warnings.push(targetSchedule.notice);if(targetSchedule.courses.some(v=>v.origin===r.source&&v.id===r.courseId&&v.conflict))warnings.push('与目标日期的课程有时间冲突。');}wx.showModal({title:r.type==='cancel'?'取消这一次课程？':'确认单门课程调整',content:c.name+'\n'+(r.type==='cancel'?r.source+' 本次停课':r.source+' → '+r.target+' · 第'+r.start+'—'+r.end+'节')+(warnings.length?'\n'+warnings.join('\n'):''),success:result=>{if(result.confirm){try{storage.save({overrides,changes:preview});this.refresh();this.setData({lastSavedDate:r.target||r.source});wx.showToast({title:'已保存'});}catch(e){wx.showToast({title:'保存失败，请重试',icon:'none'});}}}});}catch(e){wx.showToast({title:e.message,icon:'none'});}},
 removeCourse(e){const key=e.currentTarget.dataset.key;wx.showModal({title:'恢复原课程安排？',content:'删除这一条单门调整，原始日期的课程将恢复。',success:r=>{if(r.confirm){try{const {changes}=storage.read();const restoredDate=key.split('|')[0];delete changes[key];storage.save({overrides:storage.read().overrides,changes});this.refresh();this.setData({lastSavedDate:restoredDate});}catch(e){wx.showToast({title:'恢复失败，请重试',icon:'none'});}}}});},
 date(e){this.setData({date:e.detail.value});},source(e){this.setData({source:e.detail.value});},type(e){this.setData({type:Number(e.detail.value)});},note(e){this.setData({note:e.detail.value});},
 save(){try{stamp(this.data.date);const {overrides}=storage.read();overrides[this.data.date]=this.data.type===0?{type:'off',note:this.data.note.trim()||'临时停课'}:{type:'makeup',source:this.data.source};daySchedule(this.data.date,overrides);storage.save({overrides,changes:storage.read().changes});this.refresh();this.setData({lastSavedDate:this.data.date});wx.showToast({title:'已保存'});}catch(e){wx.showToast({title:'保存失败：'+e.message,icon:'none'});}},
 remove(e){const date=e.currentTarget.dataset.date;wx.showModal({title:'删除 '+date+' 的整天调整？',content:'删除后恢复原始校历安排，单门调整仍保留。',success:r=>{if(r.confirm){try{const {overrides}=storage.read();delete overrides[date];storage.save({overrides,changes:storage.read().changes});this.refresh();this.setData({lastSavedDate:date});}catch(err){wx.showToast({title:'删除失败',icon:'none'});}}}});}
});
